# Generated by Django 4.0 on 2021-12-14 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_todo_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['complete', '-created']},
        ),
    ]
